feat: Issue Colors - Done.
DigitalHouseBrasil/projeto-0822fs-modulo-4 pull request #18
Opened 2022-12-04 18:00 UTC by brunogarcia84

Realizando o PR de cores do projeto.

2022-12-04 19:20 UTC, pianeiro requested changes
@brunogarcia84 ;


# Da análise
Realizei um _code review_ preliminar, mas suficiente para apontar as seguintes necessidades de mudança:

## 1. Mensagem de _pull request_

### Problema
Enquanto o título do _pull request_ #18 se refere à _issue_ #9 (cores), sua descrição aponta a _issue_ #8 (de definições iniciais), que já está encerrada.

### Consequências
Além da necessidade de precisão no registro do histórico do projeto,  o referenciamento de uma _issue_ na mensagem de um _pull request_ movimenta o histórico da _issue_ correspondente, o que também pode confundir o processo de documentação do projeto.

### Sugestão de possíveis resoluções
Uma eventual constatação da necessidade de reabertura de _issues_ encerradas deve ser discutida com o time. Ela só deverá ser reaberta mediante algum consenso e só poderá ser movimentada se anteriormente reaberta. Portanto, se há a constatação da necessidade de reabertura da _issue_ #8 , utilize a plataforma para expor suas razões antes de tudo.

Por outro lado, se a menção à _issue_ #8 foi equivocada, sendo a correta a _issue_ #9 , a solução parece ser a edição da mensagem para corrigí-la.


## 2. Do código

### Problema
Assumindo que a _issue_ em apreço é a #9 , é possível verificar a presença de diversos incrementos de código que **NÃO** estão no escopo da paleta de cores. Dentre eles, podem ser citados regras de posicionamento nas linhas 31~37, regras de tipogradia na linha 47, entre outros.

###Consequências
Lidar com incrementos de código de várias _issues_ não é uma boa prática por violar a premissa de que um problema maior é melhor resolvido pela divisão dele em partes menores. Em alguns casos, onde o relacionamento de duas _issues_ é indissociável, isso é suportável, mas não parece ser o caso.  Além disso, o histórico de _incrementos_ envolvendo várias _issues_ dificulta o controle de versão.

### Sugestões de possíveis soluções
Separe os incrementos de código de modo a organizar cada _pull request_ referindo-se a cada _issue_. Não sendo possível, seja claro apontando todas as _issues_ que o _pull request_ movimenta, mencionando-os no título e referenciando-os na mensagem. O uso de _branches_ e o `git stash` podem ajudar nisso.

## 3. _Pull requests_ de códigos provisórios, trechos de teste e WIP

### Problema
Há possíveis códigos provisórios, como no trecho 31~38, e, de acordo com o que meu _code review_ preliminar permitiu perceber, os incrementos de código a título de tipografia e layout não concluem a demanda de suas respectivas _issues_, quais sejam: #10 e #14 . Além disso, não há qualquer assinalamento de incrementos _work in progress_ (WIP) na mensagem ou no título, explicando suas razões.

### Consequências
Códigos provisórios devem ser mantidos nos forks. Seu envio em _pull requests_ é expressamente não estimulado, por várias razões óbvias. _Pull requests_ WIP devem vir acompanhados de descrição detalhada de qual parcela do escopo foi atendida e qual ainda necessita de incremento e suas justificativas.

### Sugestões de possíveis soluções
Remova códigos provisórios. Evite ao máximo _pull requests_ WIP, mas documente-os e justifique-os nas raras vezes em que o fizer.

# Da decisão
Pelo exposto, retorno para alterações.

2022-12-04 22:43 UTC, brunogarcia84 commented
Analisando o review, e buscando não deixar os detalhes passarem, bem como a me enquadrar ao projeto, submeto as considerações abaixo, bem como o código atualizado somente com regras referentes à paleta de cores.

1.	Pull request message
----------------------------------------------

Sim, realmente acabou por ser uma grande distração quando do apontamento da issue #9 como sendo a correta.

2.	Do Código
----------------------------------------------

2.1.	Linhas 31~37
Das regras de posicionamento colocadas nas linhas supracitadas, fora um pequeno teste realizado e erroneamente não retirado do código final da paleta de cores. Problema resolvido com a exclusão das linhas com regras equivocadas para a Issue #8.

2.2.	Linha 47
Regra de tipografia inserida nesta e em diversas linhas de código referente à paleta de cores. Aqui, um equívoco de interpretação de minha parte. Em que pese ter pleno conhecimento que o peso da fonte se trata de uma regra de tipografia, ao ver o efeito visual de uma fonte mais escura, a mantive quando da codificação da paleta de cores. Tal erro não voltará a acontecer, uma vez que já estou ciente e atento aos problemas que isso pode acarretar ao projeto.

3.	Códigos Provisórios, WIP e testes
----------------------------------------------

Estou encontrando dificuldades em codar o nav menu. Desta feita, no intuito de realizar um teste de espaçamento entre o menu e os textos do header, coloquei o código provisório e não o retirei da folha de estilos. Erro crasso que não será cometido novamente.

4. Das considerações finais
----------------------------------------------

Ciente de todos os equívocos cometidos, ficarei mais atento aos requisitos do projeto, bem como buscarei seguir à risca todas as tasks propostas.

2022-12-05 05:30 UTC, pianeiro requested changes
@brunogarcia84 ;

Segue o resultado do segundo _code review_:

# Das solicitações anteriores
Analisando o atendimento às solicitações do _code review_ anterior, vejo que:
1. Embora tenha sido esclarecido o equívoco de referência à _issue_ #8, o corpo da mensagem de _pull request_ não foi editado. É necessária a substituição da referência para que a solicitação de alteração seja completamente satisfeita. Considero *PARCIALMENTE ATENDIDA*.
2. Os trechos que não se enquadram no escopo da _issue_ 9 foram retirados. Considero a solicitação *ATENDIDA*.
3. Os trechos provisórios ou incompletos foram retirados. Considero a solicitação *ATENDIDA*.

# Da análise do código

## 1. Regras de coloração faltantes
Foi possível observar algumas regras de coloração faltantes, como as regras de `color` em `.header_title` e as regras de `border-color` em `#foundations .article_illustration img`. Além disso, as regras de coloração de `.header_title em`, que, antes, estavam no código no _core review_ anterior, foram suprimidas (a mensagem de _code review_ falava apenas da linha 47, ou seja: da regra de _font-weight_ e não de todo o bloco).

Solicito a inserção das regras de coloração supra e uma revisão minuciosa das demais para que se certifique de que não há regras de coloração faltantes. Lembre que todo aspecto da página que mudaria com uma eventual alteração da paleta de cores é uma regra de coloração.

## 2. Especificidade exagerada
Foi possível encontrar seletores com níveis de especificidade claramente altos demais. Um exemplo pode ser `#project > .article > .article_title` (linha 41), onde o combinador de ancestralidade `>` é claramente desnecessário.

Requisito, objetivamente, que revise os seletores de modo a identificar especificidades claramente desnecessárias. Sugiro, subjetivamente, que adote a mínima especificidade possível. Por exemplo, a linha 41 poderia ser satisfeita utilizando o seletor `#project .article_title` sem qualquer prejuízo.

## 3. _Overrides_ e código sujo causados por despadronização na especificidade dos seletores
Um dos principais problemas causados por problemas de especificidade é o _override_ de regras não intencional. Há pelo menos um no código: `.article_text:nth-child(2)`, na linha 54, está tomando _override_ de todos outros seletores mais específicos do que ele, como os das linhas 45 e 66.

Solicito que revise o código a fim de identificar e corrigir _bugs_ de especificidade e revise a estratégia de definição de seletores a fim de manter sempre a menor especificidade possível (vide apontamento anterior).

### 4. Distinção de cores entre parágrafos de uma mesma seção
Pude perceber algumas regras de coloração que atingem apena algum dos parágrafos de uma seção, como nas linhas 58 e 66. No design do site, não há essas distinções.

# Da decisão
Pelo acima exposto, retorno o _pull request_ para a adequação.

2022-12-06 00:04 UTC, brunogarcia84 commented
Das solicitações antigas
-----------------------------------------

Alterado o número da issue de forma a enquadrar o PR à tarefa correta.

Das Regras de coloração faltantes
-----------------------------------------

Os problemas apontados no code review foram refatorados, a saber:

* #header => Adicionadas as regras de coloração do .header_title em;
* #foundations => Adicionado o background-color de acordo com a variavel grey; adicionada a borda. Neste ponto, um adendo deve ser feito. Em que pese o code review especificar o border-color, somente à título de efeito visual, fora adicionada a borda completa. É sabido que a borda deveria ser adicionada somente nas regras de estilo da página, e como expressamente solicitado anteriormente, adiciono as razões pelas quais o código segue como está. Por favor, se for uma má prática, permita-me saber para que isso não volte a se repetir. 

Entendo também ser uma afronta ao time, mas como conversado de forma privada, alterei todas as regras de coloração dos textos. Onde estavam especificadas pela cor white, de forma hard-code, alterei pela variável var(--white). Aqui, mais uma vez peço a gentileza de informar se se trata de uma má prática a alteração sem a abertura de uma issue específica, ou até mesmo antes de o time ser informado.

Da especificidade exagerada
-----------------------------------------

Aqui, também como discutimos em reunião, procurei adaptar o código para que as regras de especificidade se enquadrem às boas práticas. Tudo foi corretamente entendido, bem como irei me dedicar ainda mais aos estudos de seletores em CSS.

Dos overrides causados pelo equívoco de especificidade
-----------------------------------------

Os bugs foram corrigidos.

Da distinção de cores entre parágrafos de uma mesma seção
-----------------------------------------

Aqui também houve um problema de interpretação do design. O que é font-weight, houve uma interpretação equivocada com a cor do parágrafo e, por este motivo, o código continha referida distinção. Após a reunião, com o esclarecimento, houve a correção de referidos equívocos.

2022-12-06 18:03 UTC, pianeiro requested changes
@brunogarcia84 ;

Preliminarmente, não vejo impedimento à correção do _bug_ de cor identificado no projeto do Figma. Ademais, segue meu parecer resultante do terceiro _code review_.

# Da análise das solicitações anteriores

Analisando o atendimento às solicitações do code review anterior, vejo que:

 - Percebo a edição da mensagem de _commit_ substituindo a referência da _issue_ equivocada pela correta. Considero a solicitação **ATENDIDA**.
 - Ainda há regras de coloração não atendidas. Pode-se perceber, por exemplo, que `.header_title` não possuir a coloração devida, estando com os valores de cores _default_. Considero a solicitação **PARCIALMENTE ATENDIDA**, devendo haver meticulosa revisão nas regras para que todas sejam especificadas conforme o projeto de _design_ do Figma.
 - Percebo o ajuste de especificidade dos seletores. Considero a solicitação **ATENDIDA**.
 - Percebo e a remoção da regra `.article_text:nth-child(2)`, que causava _overrides_ indesejados. Muito embora tenha sido introduzido novo _bug_ da mesma natureza -- devidamente descrito em momento próprio --, como este _bug_ específico foi removido, considero a solicitação **ATENDIDA**.
 - Percebo a remoção da distinção entre cores de parágrafros. Considero a solicitação **ATENDIDA**.

# Da análise do código 

## 1. Introdução de novo _bug_ de _override_
O seletor `.article_text`, acrescentado por último à linha 60, atinge todos os elementos com a classe `article_text` por ser indesejamente pouco específico, já que é sobrescrito por outros seletores mais específicos, como nas linhas 51 e 68. 

## 2. Códigos fora de escopo
A inserção da regra de coloração de `#foundations .article_illustration img` através do atalho 'border` introduziu incrementos de código que estão no escopo de estilo, portanto fora do escopo da  _issue_ #9, que se limita à coloração. Embora o acréscimo das definições de estilo sejam imprescindíveis para que as regras de cor produzam resultado visual na página, o projeto persegue o não acoplamento de escopos no código.

# Da decisão
Pelo exposto, devolvo o _pull request_ para as alterações necessárias.

2022-12-06 21:04 UTC, brunogarcia84 commented
Atendendo às solicitações, seguem as alterações feitas:

Da coloração do título
---------------------------------------------

Realizada a codificação da coloração do .header_title, para que se retire a coloração padrão desta classe.

Do novo bug introduzido
---------------------------------------------

Fora corrigido o problema, com a colocação do ID #responsiveness antes da classe .article_text

Do Escopo da issue
---------------------------------------------

Retirada a codificação da borda na imagem em #foundations .article_illustration > img, deixando somente a border-color.

2022-12-06 21:32 UTC, pianeiro approved these changes
@brunogarcia84 ;

O _code review_ realizado por mim considera todas as necessidades de alteração **INTEGRALMENTE SATISFEITAS** e não identificou outras necessidades de alteração.

_Pull request_ aprovado.

2022-12-06 21:36 UTC, merged